# GitHub Pages Configuration
# CBAM Producer Data Package Specification

title: "CBAM Producer Data Package Specification"
description: >-
  Especificação técnica pública do formato de troca de dados de emissões 
  entre produtores de países terceiros e importadores europeus no contexto 
  do CBAM (Carbon Border Adjustment Mechanism) da União Europeia.

# URL Settings
baseurl: "/cbam-spec"
url: "https://rgtmaia.github.io"

# Theme
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# SEO
author: "CBAM Spec Contributors"
lang: "pt-BR"

# Google Analytics
google_analytics: G-GFBFPPKRGR

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

# Exclude from build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore
